%% Stock Screener Workflow
% Screen for large-cap technology companies.

client = fmp.Client;

screen = client.stockScreener( ...
    sector="Technology", ...
    marketCapMoreThan=1e11, ...
    betaMoreThan=0, ...
    limit=25);

disp(screen(:, ["symbol", "companyName", "marketCap", "beta"]))
