function tf = isRetriableError(exception)
%isRetriableError True for transient FMP or HTTP failures.

identifier = string(exception.identifier);
message = lower(string(exception.message));

tf = ismember(identifier, [ ...
    "fmp:RateLimit", ...
    "fmp:HttpTimeout", ...
    "fmp:HttpServerError"]) || ...
    contains(message, "rate limit") || ...
    contains(message, "too many requests") || ...
    contains(message, "timed out") || ...
    contains(message, "timeout") || ...
    ~isempty(regexp(message, "status\s*5\d\d|http\s*5\d\d", "once"));
end
